config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    end

  devise_for :users
  resources :listings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "listings#index"

  get "/payments/success", to: "payments#success"
  post "/payments/", to: "payments#create_payment_intent", as: "create_payment_intent"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one :transactions
  has_one_attached :image # trigger active storage 
  has_many :features_listings, dependent: :destroy
  has_many :features, through: :features_listings

  before_validation :convert_price_to_cents, if: :price_changed?
  before_save :remove_whitespace
  validates :name, presence:true # needs to have name
  validates :price, presence:true # needs to have price

  scope :sold, -> { joins(:transactions)}

  # % signs allow results to be returned whether there is additional words on either side of the search query (i.e. a search of "Tuna" would return "John West Tuna cans")
  scope :search_by_name, -> (name) { where('name ILIKE ?', "%#{name}%") }
  scope :filter_by_category, -> (id) {where(category_id: id) }

  # name length 
  # numericality for price 
  # comment belongs_to user 
  # listing has many comments 

  def self.search(search_hash)
    if search_hash
      if search_hash["category_id"] == ""
        Listing.search_by_name(search_hash["name"])
      else
        Listing.search_by_name(search_hash["name"]).filter_by_category(search_hash["category_id"])
      end   
    else 
      Listing.all
    end
end

def convert_price_to_cents 
  self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
end 

def remove_whitespace 
  self.name = self.name.strip
  self.description = self.description.strip
end 

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :authenticate_user!, except: %i[index show]
    before_action :find_listing, only: %i[show edit update destroy]
    before_action :set_form_variables, only: %i[new edit]

    def index
        # Eager load the listings
        @listings = Listing.search(params[:search]).includes(:user, :category)
        # Load the categories so a user can filter by category 
        @categories = Category.all
    end

    def authenticate_user
    end

    def show
    end

    def new
        # this sends @listing to new.html.erb 
        @listing = Listing.new
    end

    def create 
        # Create a new listing for the current user 
        @listing = current_user.listings.new(listings_params)
        
        respond_to do |format|
            if @listing.save
                format.html { redirect_to @listing, notice: "Listing was successfully created." }
                format.json { render :show, status: :created, location: @listing }                
            else
                set_form_variables
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @listing.errors, status: :unprocessable_entity }            
            end
        end
    end

    def edit
    end

    def update
        # Update the listing for the current user 
        respond_to do |format|
            if @listing.update(listings_params)
                format.html { redirect_to @listing, notice: "Listing was successfully updated." }
                format.json { render :show, status: :ok, location: @listing }
              else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @listing.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        # Destroy the current listing
        @listing.destroy 
        respond_to do |format|
            format.html { redirect_to root_path, notice: "Listing was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private
    
    # Use callbacks to share common setup or constraints between actions.
    def find_listing
        # Locate the current listing according to params id
        @listing = Listing.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def listings_params
        # because in the create method we already allocate listings to current user, it will already be able to access user_id, so we don't need to specify user_id here:
        params.require(:listing).permit(:name, :image, :description, :price, :category_id)
    end

    def set_form_variables
        # Get all the categories 
        @categories = Category.all
        # Get all the features 
        @features = Feature.all
      end 
    
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>

<div class="form-group mb-3">
    <%= form.label :image %>
    <%= form.file_field :image %>

</div>
<div class="form-group mb-3">
   <%= form.label :category_id, class:"col form-label" %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]}, class: "form-select" %>


</div>
<div class="form-group mb-3">
    <%= form.label :description %>
    <%= form.text_field :description, size: 30 %>

</div>
<div class="form-group mb-3">
    <%= form.label :price %>
    <%= form.number_field :price %>
    </div>

    <div class="actions">
    <%= form.submit %>
    </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit <%= @listing.name %></h1>

<%= render 'form', listing: @listing %>
<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="container-fluid align-items-center d-flex flex-column">
  <h1>What are you hungry for?</h1>
  <%= form_with(method: 'get', url: listings_path, scope: :search, local: true) do |f|%>
    <%= f.label :name, class: 'text-uppercase' %>
    <%= f.text_field :name %>
    <%= f.label :category_id, class: 'text-uppercase' %>
    <%= f.select :category_id, @categories.map {|c| [c.name, c.id] }, :include_blank => true %>
    <%= f.submit "Search" %>
  <% end %>
  <div class="container d-flex listings-container">
    <div class="row d-flex flex-row mt-1 mb-1">
      <% @listings.each do |listing| %>
        <div class=" col d-flex flex-column mt-3 mb-3 listing-wrapper shadow-lg p-3 mb-5 rounded">
          <div class="row d-flex flex-row align-items-center flex-wrap">
            <div class="col-7 d-flex flex-column align-items-start">
              <h3> <%= listing.name %></h3>
            </div>
            <div class="col d-flex flex-column align-items-end">
              <h6 class="label label-inverse"> <%= listing.category.name %></h5>
            </div>
          </div>
          <p><%= listing.description %></p>
          <% if listing.image.attached? %>
            <div class="listing-image">
              <%= image_tag url_for(listing.image), width: '250px', class: "shadow-sm mt-3 mb-3 rounded" %>
            </div>
          <% end %>
          <div class="row listings-buttons">
            <% if user_signed_in? && current_user.id == listing.user.id %>
              <div class="col d-flex flex-column">
                <%= link_to "View", listing_path(listing), class: "btn btn-primary text-white" %>
              </div>
              <div class="col d-flex flex-column">
                <%= link_to "Edit", edit_listing_path(listing), class: "btn btn-secondary text-white" %>
              </div>
              <div class="col d-flex flex-column">
                <%= link_to "Delete", listing_path(listing), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger text-white" %>
              </div>
            <% else %>
              <div class="col d-flex flex-column justify-content-center">
                <%= link_to "View", listing_path(listing), class: "btn btn-primary text-white" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<h1>Add a new listing here</h1>




<%= render 'form', listing: @listing, categories: @categories %>
<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class='container d-flex flex-column flex-md-row px-2 my-2 my-md-5'>
  <div class='d-flex flex-row w-100 listing-wrapper shadow-lg'>
    <div class='col d-flex flex-column p-0'>
      <% if @listing.image.attached? %>
        <%= image_tag url_for(@listing.image)%>
      <% end %>
    </div>
    <div class='col d-flex flex-column p-3 listing-content'>
      <div class="row d-flex flex-row align-items-center flex-wrap">
        <div class="col-7 d-flex flex-column align-items-start">
          <h3> <%= @listing.name %></h3>
        </div>
        <div class="col d-flex flex-column align-items-end">
          <h6 class="label label-inverse"> <%= @listing.category.name %></h5>
        </div>
      </div>
      <div class="row" >
        <h5>Price: <%= "$#{@listing.price / 100.0}" %></h5>
      </div>
      <div class="row">
        <p><%= @listing.description %></p>
        <p class="text-right">
          Posted by <%= @listing.username %> on <%= @listing.date_created %>.</p>
      </div>
      <div class="row">
        <%@listing.features.each do |feature|%>
          <span class='badge badge-pill badge-info'><%=feature.name%></span>
        <%end%>
      </div>
      <div class='container'>
        <div class ='d-flex justify-content-evenly'>
          <!-- only let the user who created the listing edit and delete it -->
          <% if user_signed_in? && current_user.id == @listing.user.id %>
            <%= link_to "Edit", edit_listing_path(@listing), class: "btn btn-warning mr-3" %>
            <%= link_to "Delete", @listing, method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-danger mr-3" %>
          <%elsif user_signed_in?%>
            <%if @listing.sold%>
              <button disabled>Sold</button>
            <%else%>
              <%= button_to "Buy: $#{@listing.price / 100.0}", create_payment_intent_path, method: :post, remote: true, params:{id: @listing.id}, class: "btn btn-primary p-3"%>
            <%end%>
          <%else%>
            <%=button_to "Login to buy", new_user_session_path, class: "btn btn-info"%>
          <% end %>
        </div>
        <%= link_to 'Back', listings_path %>
      </div>
      <script src="https://js.stripe.com/v3/"></script>